permalink: /:categories/:year/:month/:day/:title
baseurl: /myBlog
production_url : https://pengshahk.github.io
markdown: kramdown
highlighter: pygments


# paginate fenye
paginate: 4
paginate_path: "page:num"
gems: [ jekyll-paginate ]

# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : ycps



